# Generated by Django 4.2.1 on 2023-10-05 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='size',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
