# Generated by Django 4.2.1 on 2023-10-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cream', '0002_icecream_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecream',
            name='size',
        ),
    ]
